# Generated by Django 6.0.3 on 2026-04-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='careers/'),
        ),
    ]
