# Generated by Django 6.0.3 on 2026-04-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
