# Generated by Django 6.0.3 on 2026-04-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='plot_size_katha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='plot_size_sqft',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
